[package]
name = "rusbmux"
version = "0.1.0"
edition = "2024"
authors = ["Abdullah Al-Banna"]
description = "A drop-in usbmuxd replacement in Rust that works without a system daemon."
documentation = "https://docs.rs/rusbmux"
homepage = "https://github.com/abdullah-albanna/rusbmux"
license = "MIT"
keywords = ["apple", "usb", "usbmuxd"]

[dependencies]
rusb = "0.9"
plist-macro = "0.1"
plist = "1.8.0"

bytemuck = "1"
libc = "0.2.180"

nusb = { version = "0.2", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
